# Generated by Django 3.1.4 on 2022-07-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_categoryplantillas_productplantillas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productplantillas',
            name='image_p',
        ),
        migrations.AddField(
            model_name='productplantillas',
            name='image_p0',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productplantillas',
            name='image_p1',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productplantillas',
            name='image_p2',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
